name: Build Release APK

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout_step
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        id: validate_gradle_wrapper_step
        uses: gradle/wrapper-validation-action@v1

      - name: Decode Release Keystore
        id: decode_release_keystore_step
        env:
          RELEASE_STORE_BASE64: ${{ secrets.RELEASE_STORE_BASE64 }}
          RELEASE_STORE_FILE_PATH: /home/runner/work/_temp/keystore
        run: |
          mkdir $RELEASE_STORE_FILE_PATH
          echo $RELEASE_STORE_BASE64 | base64 -di > $RELEASE_STORE_FILE_PATH/${{ secrets.RELEASE_STORE_FILE_NAME }}

      - name: Setup JDK
        id: setup_jdk_step
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 11

      - name: Setup Gradle
        id: setup_gradle_step
        uses: gradle/gradle-build-action@v2

      # Gradle files created from Windows may require permission, two options to fix:
      # first option is run the following command on your project: git update-index --chmod=+x gradlew
      # second option is to create a step to run every time along with the workflow:
      - name: Permission to Gradlew
        id: permission_gradlew_step
        run: chmod +x gradlew

      - name: Build Release APK
        id: build_release_apk_step
        env:
          RELEASE_STORE_FILE: /home/runner/work/_temp/keystore/${{ secrets.RELEASE_STORE_FILE_NAME }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          # Workaround to avoid exception with signing on debug build.
          DEBUG_STORE_FILE: unknow-key
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload Artifact
        id: upload_artifact_step
        uses: actions/upload-artifact@v3
        with:
          name: Release Artifacts
          path: app/build/outputs/
